# Generated by Django 2.2.19 on 2021-03-31 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mercado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=250)),
                ('nomeProduto', models.CharField(max_length=200)),
                ('valor', models.IntegerField(verbose_name=0)),
                ('dataCompra', models.CharField(max_length=50)),
                ('chave', models.CharField(max_length=50)),
                ('dataPublicacao', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
