# Generated by Django 2.2.19 on 2021-03-31 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='Mercado',
            new_name='mercado',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='preco',
        ),
    ]
