# Generated by Django 2.2.19 on 2021-03-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0002_auto_20210330_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.CharField(max_length=50),
        ),
    ]
