# Generated by Django 3.1.7 on 2021-05-05 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0005_auto_20210505_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 16, 8, 139770, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 16, 8, 139770, tzinfo=utc)),
        ),
    ]
