# Generated by Django 2.2.19 on 2021-03-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0006_auto_20210331_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='chave',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dataCompra',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dataPublicacao',
            field=models.DateTimeField(),
        ),
    ]
