# Generated by Django 2.2.19 on 2021-03-31 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_auto_20210331_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='chave',
            field=models.CharField(max_length=50),
        ),
    ]
