# Generated by Django 3.1.7 on 2021-05-05 14:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0007_auto_20210505_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 20, 18, 419605, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='acesso',
            name='nome',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 5, 14, 20, 18, 419605, tzinfo=utc)),
        ),
    ]
