# Generated by Django 3.1.7 on 2021-04-06 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0008_auto_20210331_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='author',
        ),
    ]
