# Generated by Django 3.1.7 on 2021-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0009_remove_produto_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cnpj',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AddField(
            model_name='produto',
            name='fantasia',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
