# Generated by Django 3.2.3 on 2021-05-15 00:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0010_auto_20210513_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 0, 27, 18, 198352, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 0, 27, 18, 198352, tzinfo=utc)),
        ),
    ]
