# Generated by Django 2.0.7 on 2021-05-15 03:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0011_auto_20210514_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acesso',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 3, 47, 9, 152041, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 15, 3, 47, 9, 152041, tzinfo=utc)),
        ),
    ]
